### ISSUE TITLE
Missing shapefiles

### ISSUE THREAD

**Issue by matts-maps** [mapaction/mapactionpy_controller#105]
Not sure if this is the right place so please move if it isn't - it would be good for jira to say if a shapefile is missing from the receipe. Current, there can be no faults with the naming convention however if a file is missing you don't know until you look the mxds, or the output report.

**Comment by andrewphilipsmith** [comment]
This will be included in v1.1, along with Jira tickets for a number of other senarios (eg wrong schema etc)

**Comment by andrewphilipsmith** [comment]
Fixed by https://github.com/mapaction/mapactionpy_controller/pull/98
